# Generated by Django 4.0.4 on 2022-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
