# Generated by Django 4.0.4 on 2022-04-20 23:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('file_archive', '0002_alter_archive_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
    ]
